module

public import Mathlib.GroupTheory.Torsion
public import Mathlib.Data.Nat.Factorization.Basic
public import Mathlib.Algebra.IsPrimePow
public import SKW.Prereqs.AlgebraMisc

@[expose] public section

/-!
# Primary components generate a torsion commutative group

In a torsion commutative group, the `p`-primary components (`CommGroup.primaryComponent`) jointly
generate the whole group (`CommGroup.iSup_primaryComponent_eq_top`); equivalently, the elements of
prime power order generate it (`CommGroup.closure_isPrimePow_orderOf_eq_top`).

These mirror the module-theoretic `iSup_primaryComponent_eq_top` and are intended for upstreaming to
`Mathlib/GroupTheory/Torsion.lean`.
-/

/-- If `a` and `b` are coprime, then `g` lies in the subgroup generated by `g ^ a` and `g ^ b`
(a special case of `Subgroup.zpowers_zpow_sup`, since `Nat.gcd a b = 1`). -/
theorem mem_sup_zpowers_pow_of_coprime {G : Type*} [Group G] {a b : ℕ}
    (h : Nat.Coprime a b) (g : G) :
    g ∈ Subgroup.zpowers (g ^ a) ⊔ Subgroup.zpowers (g ^ b) := by
  rw [← zpow_natCast g a, ← zpow_natCast g b, Subgroup.zpowers_zpow_sup,
    Int.gcd_natCast_natCast, h.gcd_eq_one, Nat.cast_one, zpow_one]
  exact Subgroup.mem_zpowers g

namespace CommGroup

variable {G : Type*} [CommGroup G]

/-- Auxiliary form of `mem_iSup_primaryComponent_primeFactors`, with `orderOf x` abstracted as `n`,
so that the proof can recurse on the prime-power factorization of `n`. -/
theorem mem_iSup_primaryComponent_primeFactors_aux {n : ℕ} {x : G} (hn : 0 < n) (hx : orderOf x = n) :
    x ∈ ⨆ q ∈ n.primeFactors, primaryComponent G q := by
  induction n using Nat.recOnPrimePow generalizing x with
  | zero =>
      exact False.elim <| Nat.not_succ_le_zero 0 hn
  | one => simpa using hx
  | prime_pow_mul m p k hp hpm hk h_ind =>
      have : Fact p.Prime := ⟨hp⟩
      have hm : 0 < m := by
        contrapose! hn
        simp_all
      have hcop : m.Coprime (p ^ k) := by
        rw [Nat.coprime_pow_right_iff hk, Nat.coprime_comm]
        exact (Nat.Prime.coprime_iff_not_dvd hp).mpr hpm
      rw [hcop.symm.primeFactors_mul, Nat.primeFactors_prime_pow (ne_of_gt hk) hp,
        Finset.singleton_union, Finset.iSup_insert]
      refine mem_of_le_of_mem (sup_le_sup ?_ ?_) (mem_sup_zpowers_pow_of_coprime hcop x)
      · refine Subgroup.zpowers_le.mpr ?_
        rw [CommGroup.mem_primaryComponent_iff_orderOf,
          orderOf_pow_of_orderOf_eq_mul (by linarith) (by rwa [mul_comm])]
        exact ⟨k, rfl⟩
      · refine Subgroup.zpowers_le.mpr <| h_ind hm ?_
        rw [orderOf_pow_of_orderOf_eq_mul (by linarith) hx]

/-- A finite-order element lies in the join of the `p`-primary components, for `p` ranging over the
primes dividing its order. -/
theorem mem_iSup_primaryComponent_primeFactors {x : G} (hx : IsOfFinOrder x) :
    x ∈ ⨆ q ∈ (orderOf x).primeFactors, primaryComponent G q :=
  mem_iSup_primaryComponent_primeFactors_aux hx.orderOf_pos rfl

/-- Every element of a torsion commutative group lies in the join of its `p`-primary components. -/
theorem mem_iSup_primaryComponent (hG : IsMulTorsion G) (g : G) :
    g ∈ ⨆ p : Nat.Primes, primaryComponent G p := by
  refine mem_of_le_of_mem ?_ <| mem_iSup_primaryComponent_primeFactors (hG g)
  rw [show ⨆ p : Nat.Primes, primaryComponent G p = ⨆ p ∈ {n | Nat.Prime n}, primaryComponent G p
    from iSup_subtype]
  exact biSup_mono fun h hp ↦ (Nat.mem_primeFactors.mp hp).1

/-- In a torsion commutative group, the primary components generate the whole group. -/
theorem iSup_primaryComponent_eq_top (hG : IsMulTorsion G) :
    ⨆ p : Nat.Primes, primaryComponent G p = ⊤ :=
  eq_top_iff.mpr fun g _ ↦ mem_iSup_primaryComponent hG g

/-- In a torsion commutative group, the elements of prime power order generate the whole group. -/
theorem closure_isPrimePow_orderOf_eq_top (hG : IsMulTorsion G) :
    Subgroup.closure {x : G | IsPrimePow (orderOf x)} = ⊤ := by
  rw [eq_top_iff, ← iSup_primaryComponent_eq_top hG,  iSup_le_iff]
  intro p x hx
  have : Fact p.val.Prime := ⟨p.prop⟩
  obtain ⟨k, hx'⟩ := mem_primaryComponent_iff_orderOf.mp hx
  by_cases hk : 0 < k
  · exact Subgroup.mem_closure_of_mem ⟨p, k, Nat.prime_iff.mp p.prop, hk, hx'.symm⟩
  · simp_all

end CommGroup

end
