module

public import Mathlib.RingTheory.ZMod.UnitsCyclic
public import Mathlib.Data.ZMod.Units
public import Mathlib.GroupTheory.Complement
public import Mathlib.GroupTheory.SpecificGroups.Cyclic

set_option linter.style.header false

public section

/-!
# The unit group of `ZMod (2 ^ k)` modulo `±1`

The subgroups generated by `5` and by `-1` are complements in `(ZMod (2 ^ (n + 2)))ˣ`, so the
quotient by `⟨-1⟩` is cyclic of order `2 ^ n`, generated by the class of `5`.
-/

section

theorem ZMod.unitsMap_neg {n m : ℕ} (hm : n ∣ m) (a : (ZMod m)ˣ) :
    unitsMap hm (-a) = - unitsMap hm a := by
  simp [unitsMap_def]

end

namespace Units

/-- The order of `-1` in the unit group of a ring. -/
theorem orderOf_neg_one {R : Type*} [Ring R] [Nontrivial R] :
    orderOf (-1 : Rˣ) = if ringChar R = 2 then 1 else 2 := by
  rw [← orderOf_units, Units.val_neg, Units.val_one, _root_.orderOf_neg_one]

end Units

namespace ZMod

def unitFive {n : ℕ} : (ZMod (2 ^ n))ˣ :=
  unitOfCoprime 5 <| by cases n <;> norm_num

@[simp]
theorem unitFive_val {n : ℕ} : unitFive.val = (5 : ZMod (2 ^ n)) := by rfl

theorem unitFive_cast {n d : ℕ} (h : d ∣ 2 ^ n) (R : Type*) [Ring R] [CharP R d] :
    ZMod.castHom h R unitFive.val = 5 := by
  rw [unitFive_val, map_ofNat]

/-- Reducing `5` modulo `4` gives `1`. -/
theorem unitsMap_four_unitFive (n : ℕ) :
    ZMod.unitsMap (by grind : 4 ∣ 2 ^ (n + 2)) unitFive = 1 := by
  ext
  rw [ZMod.unitsMap_def, Units.coe_map, MonoidHom.coe_ofClass, unitFive_cast]
  decide

/-- The subgroups generated by `5` and by `-1` in `(ZMod (2 ^ (n + 2)))ˣ` are disjoint, since `5`
reduces to `1` modulo `4` while `-1` reduces to `3`. -/
theorem disjoint_zpowers_unitFive_neg_one (n : ℕ) :
    Disjoint (Subgroup.zpowers unitFive)
      (Subgroup.zpowers (-1 : (ZMod (2 ^ (n + 2)))ˣ)) := by
  have : Nontrivial (ZMod 4) := ZMod.nontrivial_iff.mpr <| by norm_num
  have h : ringChar (ZMod 4) ≠ 2 := by
    rw [ZMod.ringChar_zmod_n]
    norm_num
  refine Subgroup.disjoint_def.mpr ?_
  rintro x ⟨k, rfl⟩ ⟨l, hl⟩
  suffices Even l by simp [← hl, neg_one_zpow_eq_ite, ite_eq_left this]
  have := congr_arg (ZMod.unitsMap (by grind : 4 ∣ 2 ^ (n + 2))) hl
  simpa only [map_zpow, unitsMap_four_unitFive, one_zpow, ZMod.unitsMap_neg, map_one,
    ← orderOf_dvd_iff_zpow_eq_one, Units.orderOf_neg_one, ite_eq_right h, Nat.cast_ofNat,
    ← even_iff_two_dvd]

/-- The subgroups generated by `5` and by `-1` are complements in `(ZMod (2 ^ (n + 2)))ˣ`. -/
theorem isComplement'_zpowers_unitFive_neg_one (n : ℕ) :
    (Subgroup.zpowers unitFive).IsComplement'
      (Subgroup.zpowers (-1 : (ZMod (2 ^ (n + 2)))ˣ)) := by
  have : Nontrivial (ZMod (2 ^ (n + 2))) := ZMod.nontrivial_iff.mpr (by grind)
  refine Subgroup.isComplement'_of_card_mul_and_disjoint ?_ (disjoint_zpowers_unitFive_neg_one n)
  rw [Nat.card_zpowers, Nat.card_zpowers, ← orderOf_units, unitFive_val, ZMod.orderOf_five,
    Units.orderOf_neg_one, ZMod.ringChar_zmod_n, ite_eq_right (by grind),
    Nat.card_eq_fintype_card, ZMod.card_units_eq_totient,
    Nat.totient_prime_pow Nat.prime_two (by norm_num), Nat.add_one_sub_one,
    Nat.add_one_sub_one, mul_one, pow_succ]

/-- The quotient of `(ZMod (2 ^ (n + 2)))ˣ` by `⟨-1⟩` is cyclic, generated by the class of `5`. -/
theorem isCyclic_units_two_pow_quotient_neg_one (n : ℕ) :
    IsCyclic ((ZMod (2 ^ (n + 2)))ˣ ⧸ Subgroup.zpowers (-1)) :=
  (isComplement'_zpowers_unitFive_neg_one n).QuotientMulEquiv.isCyclic.mpr inferInstance

/-- The class of `5` generates the quotient of `(ZMod (2 ^ (n + 2)))ˣ` by `⟨-1⟩`. -/
theorem zpowers_mk_unitFive_eq_top (n : ℕ) :
    Subgroup.zpowers (QuotientGroup.mk unitFive :
      (ZMod (2 ^ (n + 2)))ˣ ⧸ Subgroup.zpowers (-1 )) = ⊤ := by
  have := congr_arg (Subgroup.map (QuotientGroup.mk' (Subgroup.zpowers
    (-1 : (ZMod (2 ^ (n + 2)))ˣ)))) (isComplement'_zpowers_unitFive_neg_one n).sup_eq_top
  rwa [Subgroup.map_sup, Subgroup.map_top_of_surjective _ (QuotientGroup.mk'_surjective _),
    MonoidHom.map_zpowers, MonoidHom.map_zpowers, QuotientGroup.mk'_apply,
    sup_eq_left.mpr] at this
  simp [QuotientGroup.mk'_apply, (QuotientGroup.eq_one_iff _).mpr (Subgroup.mem_zpowers _)]

end ZMod
