module

public import Mathlib.RingTheory.ZMod.UnitsCyclic
public import Mathlib.Data.ZMod.Units
public import Mathlib.GroupTheory.Complement
public import Mathlib.GroupTheory.SpecificGroups.Cyclic

public section

/-!
# The unit group of `ZMod (2 ^ k)` modulo `±1`

The subgroups generated by `5` and by `-1` are complements in `(ZMod (2 ^ (n + 2)))ˣ`, so the
quotient by `⟨-1⟩` is cyclic of order `2 ^ n`, generated by the class of `5`.
-/

namespace Nat

/-- The totient of a power of two. -/
theorem totient_two_pow (n : ℕ) : (2 ^ (n + 1)).totient = 2 ^ n := by
  rw [Nat.totient_prime_pow Nat.prime_two n.succ_pos, Nat.add_one_sub_one]
  norm_num

end Nat

namespace Units

/-- The order of `-1` in the unit group of a ring. -/
theorem orderOf_neg_one {R : Type*} [Ring R] [Nontrivial R] :
    orderOf (-1 : Rˣ) = if ringChar R = 2 then 1 else 2 := by
  rw [← orderOf_units, Units.val_neg, Units.val_one, _root_.orderOf_neg_one]

end Units

namespace ZMod

/-- `5` is a unit modulo `2 ^ (n + 2)`. -/
theorem isUnit_five (n : ℕ) : IsUnit (5 : ZMod (2 ^ (n + 2))) := by
  rw [show (5 : ZMod (2 ^ (n + 2))) = (5 : ℕ) by rw [Nat.cast_ofNat], ZMod.isUnit_iff_coprime]
  norm_num

/-- The unit group of `ZMod (2 ^ (n + 1))` has `2 ^ n` elements. -/
theorem card_units_two_pow (n : ℕ) : Nat.card (ZMod (2 ^ (n + 1)))ˣ = 2 ^ n := by
  rw [Nat.card_eq_fintype_card, ZMod.card_units_eq_totient, Nat.totient_two_pow]

/-- Reducing `5` modulo `4` gives `1`. -/
theorem unitsMap_isUnit_five_unit (n : ℕ) :
    ZMod.unitsMap (show 4 ∣ 2 ^ (n + 2) by grind) (isUnit_five n).unit = 1 := by
  ext
  simp [ZMod.unitsMap_val, Units.val_one]
  rw [show (5 : ZMod (2 ^ (n + 2))) = (5 : ℕ) by rfl, ZMod.cast_natCast (by grind)]
  decide

/-- The subgroups generated by `5` and by `-1` in `(ZMod (2 ^ (n + 2)))ˣ` are disjoint, since `5`
reduces to `1` modulo `4` while `-1` reduces to `3`. -/
theorem disjoint_zpowers_five_neg_one (n : ℕ) :
    Disjoint (Subgroup.zpowers (isUnit_five n).unit)
      (Subgroup.zpowers (-1 : (ZMod (2 ^ (n + 2)))ˣ)) := by
  have : Nontrivial (ZMod 4) := ZMod.nontrivial_iff.mpr <| by norm_num
  refine Subgroup.disjoint_def.mpr ?_
  rintro x ⟨k, rfl⟩ ⟨l, hl⟩
  have := congr_arg (ZMod.unitsMap (by grind : 4 ∣ 2 ^ (n + 2))) hl
  dsimp at this
  rw [map_zpow, map_zpow, unitsMap_isUnit_five_unit, one_zpow, ZMod.unitsMap_def, Units.map_neg,
    map_one, ← orderOf_dvd_iff_zpow_eq_one, Units.orderOf_neg_one, ite_eq_right,
    Nat.cast_ofNat] at this
  obtain ⟨c, rfl⟩ := this
  rw [← hl]
  simp [zpow_mul]
  rw [ZMod.ringChar_zmod_n]
  norm_num

/-- The subgroups generated by `5` and by `-1` are complements in `(ZMod (2 ^ (n + 2)))ˣ`. -/
theorem isComplement'_zpowers_five_neg_one (n : ℕ) :
    (Subgroup.zpowers (isUnit_five n).unit).IsComplement'
      (Subgroup.zpowers (-1 : (ZMod (2 ^ (n + 2)))ˣ)) := by
  have : Nontrivial (ZMod (2 ^ (n + 2))) := ZMod.nontrivial_iff.mpr (by grind)
  refine Subgroup.isComplement'_of_card_mul_and_disjoint ?_ (disjoint_zpowers_five_neg_one n)
  rw [Nat.card_zpowers, Nat.card_zpowers, ← orderOf_units, IsUnit.unit_spec, ZMod.orderOf_five,
    Units.orderOf_neg_one, ZMod.ringChar_zmod_n, card_units_two_pow]
  norm_num
  split_ifs with h <;> grind

/-- The quotient of `(ZMod (2 ^ (n + 2)))ˣ` by `⟨-1⟩` is cyclic, generated by the class of `5`. -/
theorem isCyclic_units_two_pow_quotient_neg_one (n : ℕ) :
    IsCyclic ((ZMod (2 ^ (n + 2)))ˣ ⧸ Subgroup.zpowers (-1 : (ZMod (2 ^ (n + 2)))ˣ)) :=
  (isComplement'_zpowers_five_neg_one n).QuotientMulEquiv.isCyclic.mpr inferInstance

end ZMod
